[ServerInfo]
AddresIP=177.70.19.245
Game_Port = 5816
ServerName = CoPrivate
WebSite=

[InternetPort]
BackLog = 100
ReceiveSize = 8191
SendSize = 8191
;65000
[AntiCheat]
EnablePacketFloodGuard=1
PacketFloodSoftLimit=1000
PacketFloodHardLimit=2500

[InterServer]
AddresIP=177.70.19.245
Port=9920
IsInterServer=0

[Database]
Location=Database5103\
CO2FOLDER=Database5103\
ItemUID=1156407
ClientUID=1101651
Day=108
[Tournaments]
PkWarWinner=1001082
